### PR TITLE
Mark instance as saved

### LINKED ISSUE #19: Instance.save() doesn't clear the isNewRecord flag
When calling `save()` it doesn't change the flag `.options.isNewRecord`, making impossible to test if a model was correctly saved.

```
const user = TwitterAccountMock.build({});
expect(user.options.isNewRecord).to.be.true; //OK
user.save();
expect(user.options.isNewRecord).to.be.false; //Fails
```

### PR DESCRIPTION
**Pull request by scinos**
Fixes #19

### CODE REVIEW

File: src/instance.js [hunk 1]
```diff
@@ -244,7 +244,7 @@ fakeModelInstance.prototype.save = function () {
 	return this.validate().then(function (err) {
 		if(err)
 			throw err;
-		
+		self.options.isNewRecord = false;
```
Comment (ktsashes) [inline src/instance.js]: Probably also want to add `self.isNewRecord` as well here. That seems to be the one actually documented, but both are supported

Comment (scinos) [inline src/instance.js]: Fixed
